%
x0 = [-1.2 1];
%
% other options
xlower = [-2 -2];
xupper = [2 2];
fmax   = 10.0;

[ x, fx, msg, wrn, neval, f_hist] = bfo(@(x,fmax)banana_withmax(x,fmax), x0, ...
        'epsilon', 0.0001, 'maxeval', 100, ... 
        'xlower', xlower, 'xupper', xupper, ...
        'save-freq', 10, 'restart-file', 'bfo-banana.restart', ...
        'f-call-type', 'with-bound', ...
        'f-bound', fmax);