%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/meza/MyProjects/TLEED/plotfigs/expbeam1.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/06/22 17:08:02

%% Initialize variables.
filename = '/Users/meza/MyProjects/TLEED/plotfigs/expbeamx.dat';

%% Format for each line of text containing Energy Data
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
Energy_formatSpec = '%12f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');
title = textscan(fileID, '%s',1); 


%% Each grouping of energies has 3 parts: 1) beam designation, 2) number of
%% data points, 3) actual energy values
%% In total there should be 20 such groups

for i=1:20
%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.

    num_energy = textscan(fileID, '%d%f',1);
    endRow = num_energy{1};
    dataArray = textscan(fileID, Energy_formatSpec, endRow, 'Delimiter', '', 'WhiteSpace', '', 'ReturnOnError', false, 'EndOfLine', '\r\n');
    %% Create output variable
    expbeam = [dataArray{1:end-1}];
end

%% Close the text file.
fclose(fileID);

%% Clear temporary variables
clearvars filename startRow endRow formatSpec fileID dataArray ans;